---
name: task2
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  retrofit: ^4.1.0
  auto_route: ^8.1.0
  json_annotation: ^4.8.1
  dio: ^5.4.3+1

dev_dependencies:
  auto_route_generator: ^8.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
